# ------------------------------------------------------------
# Define Error Messages in this file.
# ------------------------------------------------------------
# Page definitions moved to pages.yml.
# ------------------------------------------------------------
# After you have made changes to this file, execute 
# /help -reload
# ------------------------------------------------------------
# 
messages:
  noPagePermission: '%red%You don''t have permission for page %yellow%%page%'
  pageNotFound: '%red%Page %yellow%%page% %red%does not exist'
  pageTitle: '%aqua%Help page %white%%page%%aqua%:'